<script lang="ts">
  import {
    convertToHex,
    detectColorFormat,
    getContrastTextColor,
    hslToHsv,
    hslToRgb,
    hsvToHsl,
    isDarkColor,
    rgbToHex,
    rgbToHsl,
    hexToRgb,
  } from '$lib/color/utility'
  import { CATEGORICAL_PALETTE } from '$lib/color/palettes'

  interface Props {
    value: string
    oninput?: (color: string) => void
    palette?: string[]
  }

  let {
    value = $bindable('#000000'),
    oninput = () => {},
    palette = CATEGORICAL_PALETTE,
  }: Props = $props()

  // State for HSV model (this better matches the visual color picker)
  let hue = $state(0)
  let saturationHsv = $state(100)
  let valueHsv = $state(100)

  // State for manual text input
  let inputValue = $state(value)

  // State for tracking drag operations
  let isDragging = $state(false)
  let satLightPickerElement: HTMLDivElement | null = $state(null)

  // Track the last hex value generated by this component to avoid feedback loops
  let internalHex = $state('')

  // Initialize and sync HSV from value prop only when it changes from outside
  $effect(() => {
    if (value && value !== internalHex) {
      updateHsvFromHex(value)
      inputValue = value
      internalHex = value
    }
  })

  // Update HSV values from hex
  const updateHsvFromHex = (hexColor: string) => {
    const format = detectColorFormat(hexColor)
    if (format === 'invalid') return

    const actualHex = convertToHex(hexColor)
    const rgb = hexToRgb(actualHex)
    const hslValues = rgbToHsl(rgb.r, rgb.g, rgb.b)
    const hsvValues = hslToHsv(hslValues.h, hslValues.s, hslValues.l)

    hue = hsvValues.h
    saturationHsv = hsvValues.s
    valueHsv = hsvValues.v
  }

  // Update color from HSV
  const updateColorFromHsv = () => {
    const hslValues = hsvToHsl(hue, saturationHsv, valueHsv)
    const rgb = hslToRgb(hslValues.h, hslValues.s, hslValues.l)
    const hexValue = rgbToHex(rgb.r, rgb.g, rgb.b)

    // Update internal tracking first to prevent the effect from re-syncing
    internalHex = hexValue
    value = hexValue
    inputValue = hexValue
    oninput(hexValue)
  }

  // Handle saturation/value (brightness) change in HSV model
  const handleSatValueChange = (e: MouseEvent) => {
    if (!satLightPickerElement) return

    const rect = satLightPickerElement.getBoundingClientRect()

    // X maps directly to saturation (0-100%)
    saturationHsv = Math.max(
      0,
      Math.min(100, Math.round(((e.clientX - rect.left) / rect.width) * 100))
    )

    // Y maps inversely to value/brightness (100-0%)
    valueHsv = Math.max(
      0,
      Math.min(
        100,
        Math.round(100 - ((e.clientY - rect.top) / rect.height) * 100)
      )
    )

    updateColorFromHsv()
  }

  // Handle mouse down on saturation/value picker
  const handleSatValueMouseDown = (e: MouseEvent) => {
    e.preventDefault()
    isDragging = true

    // Prevent text selection during drag
    document.body.style.userSelect = 'none'

    handleSatValueChange(e)

    const handleGlobalMouseMove = (moveEvent: MouseEvent) => {
      if (isDragging) {
        moveEvent.preventDefault()
        handleSatValueChange(moveEvent)
      }
    }

    const handleGlobalMouseUp = (upEvent: MouseEvent) => {
      isDragging = false
      document.body.style.userSelect = ''
      window.removeEventListener('mousemove', handleGlobalMouseMove)
      window.removeEventListener('mouseup', handleGlobalMouseUp)
    }

    window.addEventListener('mousemove', handleGlobalMouseMove)
    window.addEventListener('mouseup', handleGlobalMouseUp)
  }

  // Handle manual text input
  const handleTextInput = (e: Event) => {
    const input = e.target as HTMLInputElement
    inputValue = input.value

    const format = detectColorFormat(inputValue)
    if (format !== 'invalid') {
      const hexValue = convertToHex(inputValue)
      internalHex = hexValue
      value = hexValue
      updateHsvFromHex(hexValue)
      oninput(hexValue)
    }
  }

  // Handle hue change
  const handleHueChange = (e: Event) => {
    const input = e.target as HTMLInputElement
    hue = parseInt(input.value, 10)
    updateColorFromHsv()
  }

  // Handle palette color selection
  const selectPaletteColor = (paletteColor: string) => {
    internalHex = paletteColor
    value = paletteColor
    inputValue = paletteColor
    updateHsvFromHex(paletteColor)
    oninput(paletteColor)
  }

  // Derived properties
  const selectorPosition = $derived({
    left: `${saturationHsv}%`,
    top: `${100 - valueHsv}%`,
  })

  const hueColor = $derived(`hsl(${hue}, 100%, 50%)`)
  const contrastTextColor = $derived(getContrastTextColor(value))
  const isColorDark = $derived(isDarkColor(value))
  const selectorBorderColor = $derived(isColorDark ? 'white' : 'black')
</script>

<div class="color-picker-container">
  <!-- Saturation/Value (HSV) picker -->
  <div
    class="sat-light-picker"
    style:background-color={hueColor}
    onmousedown={handleSatValueMouseDown}
    bind:this={satLightPickerElement}
    role="none"
  >
    <div
      class="sat-light-selector"
      style:left={selectorPosition.left}
      style:top={selectorPosition.top}
      style:background-color={value}
      style:border-color={selectorBorderColor}
    ></div>
  </div>

  <!-- Hue slider -->
  <div class="hue-slider-container">
    <input
      type="range"
      min="0"
      max="360"
      class="hue-slider"
      value={hue}
      oninput={handleHueChange}
    />
  </div>

  <!-- Color preview with integrated text input -->
  <div class="color-preview-container" style:background-color={value}>
    <input
      type="text"
      class="color-text-input"
      value={inputValue}
      oninput={handleTextInput}
      style:color={contrastTextColor}
      style:border-bottom-color={contrastTextColor}
    />
  </div>

  <!-- Quick color palette for common selections -->
  <div class="color-palette">
    {#each palette as paletteColor}
      <button
        type="button"
        class="palette-color"
        style:background-color={paletteColor}
        onclick={() => selectPaletteColor(paletteColor)}
        aria-label={`Select color ${paletteColor}`}
      ></button>
    {/each}
  </div>
</div>

<style>
  .color-picker-container {
    display: flex;
    flex-direction: column;
  }

  .sat-light-picker {
    position: relative;
    width: 100%;
    height: 120px;
    border-radius: 4px;
    cursor: crosshair;
    background-image:
      linear-gradient(to top, #000, transparent),
      linear-gradient(to right, #fff, transparent);
    margin-bottom: 6px;
    user-select: none;
    -webkit-user-select: none;
  }

  .sat-light-selector {
    position: absolute;
    width: 12px;
    height: 12px;
    transform: translate(-50%, -50%);
    border: 2px solid white;
    border-radius: 50%;
    box-shadow: 0 0 2px rgba(0, 0, 0, 0.6);
    pointer-events: none;
  }

  .hue-slider-container {
    margin-bottom: 6px;
  }

  .hue-slider {
    width: 100%;
    height: 12px;
    -webkit-appearance: none;
    appearance: none;
    border-radius: 4px;
    background: linear-gradient(
      to right,
      #f00 0%,
      #ff0 17%,
      #0f0 33%,
      #0ff 50%,
      #00f 67%,
      #f0f 83%,
      #f00 100%
    );
    outline: none;
    cursor: pointer;
  }

  .hue-slider::-webkit-slider-thumb {
    -webkit-appearance: none;
    appearance: none;
    width: 8px;
    height: 16px;
    border-radius: 2px;
    background: white;
    border: 1px solid #ccc;
    cursor: pointer;
  }

  .hue-slider::-moz-range-thumb {
    width: 8px;
    height: 16px;
    border-radius: 2px;
    background: white;
    border: 1px solid #ccc;
    cursor: pointer;
  }

  .color-preview-container {
    width: 100%;
    height: 28px;
    border-radius: 4px;
    margin-bottom: 6px;
    display: flex;
    align-items: center;
    justify-content: center;
  }

  .color-text-input {
    width: 90%;
    height: 80%;
    border: none;
    background: transparent;
    text-align: center;
    font-family: monospace;
    font-size: 13px;
    font-weight: 500;
    color: inherit;
    outline: none;
  }

  .color-palette {
    display: flex;
    flex-wrap: wrap;
    gap: 2px;
    justify-content: center;
  }

  .palette-color {
    width: 16px;
    height: 16px;
    border-radius: 3px;
    border: 1px solid rgba(0, 0, 0, 0.1);
    cursor: pointer;
    transition: transform 0.1s;
    padding: 0;
  }

  .palette-color:hover {
    transform: scale(1.1);
  }
</style>
